[project]
name = "pydns"
version = "0.1.0"
description = "DNS ~ Direct Numerical Simulation"
requires-python = ">=3.13,<3.14"

dependencies = [
    "matplotlib",
    "numpy",
    "pandas",
    "pillow",
    "polars",
    "pyarrow",
    "pyqt6",
    "meson",
    "ninja",
    "pyinstaller",
]